---
- name: Check if containers are running
  command: docker ps 
  register: running_containers

- name: Container status
  debug:
    var: running_containers.stdout_lines

- name: Copy dockerfile to host
  copy:
    src: "/home/ibm1/intro-ansible/exemplos_praticos/docker-compose.yaml"
    dest: /home/teste

  
# - name: Run docker compose
#   shell: docker-compose up -d
#   args:
#     chdir: "{{ home_path }}/intro-ansible/exemplos_praticos"


# - name: Teste
#   debug:
#     msg: "!!!!!!!!!!!!!!!!!!! {{ running_containers.stdout }}"

# - name: Compose u
