---
- name: Manage Docker containers
  hosts: teste
  tasks:
    - name: Check if containers are running
      command: docker ps 
      register: running_containers

    - name: Display running containers
      debug:
        var: running_containers.stdout_lines

    - name: Copy Docker Compose file to host
      copy:
        src: "{{ home_path }}/intro-ansible/exemplos_praticos/docker-compose.yaml"
        dest: "/home/teste/docker-compose.yaml"

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: "/home/teste"
